const specialDays = {
  // January
  'Jan-1': ['New Year'],
  'Jan-10': ['World Laughter Day'],
  'Jan-12': ['National Youth Day'],
  'Jan-15': ['Army Day'],
  'Jan-23': ['Netaji Jayanti'],
  'Jan-25': ['Indian Tourism Day'],
  'Jan-26': ['Republic Day (India)'],
  'Jan-30': ["Martyr's Day"],
  // February
  'Feb-4': ['World Cancer Day'],
  'Feb-7': ['Rose Day'],
  'Feb-8': ['Propose Day'],
  'Feb-9': ['Chocolate Day'],
  'Feb-10': ['Teddy Day'],
  'Feb-11': ['Promise Day'],
  'Feb-12': ['Hug Day'],
  'Feb-13': ['Kiss Day'],
  'Feb-14': ['Valentine Day'],
  'Feb-15': ['Slap Day'],
  'Feb-28': ['National Science Day'],
  // March
  'Mar-3': ['National Defence Day'],
  'Mar-4': ['National Security Day'],
  'Mar-8': ["International Women's & Literacy Day"],
  'Mar-14': ['Pi Day'],
  'Mar-15': ['World Consumer Rights Day'],
  'Mar-16': ['National Vaccination Day'],
  'Mar-21': ['World Forestry Day'],
  'Mar-22': ['World Water Day'],
  'Mar-23': ['World Meteorological Day'],
  'Mar-24': ['World TB Day'],
  // April
  'Apr-1': ["Fool's day"],
  'Apr-5': ['National Maritime Day'],
  'Apr-7': ['World Health Day'],
  'Apr-17': ['World Haemophilia Day'],
  'Apr-18': ['World Heritage Day'],
  'Apr-22': ['Earth Day'],
  'Apr-23': ['World Book & Copyright Day'],
  // May
  'May-1': ['May Day', 'Labour Day'],
  'May-3': ['International Energy Day'],
  'May-4': ["International Firefighters' Day"],
  'May-8': ['World Red Cross Day'],
  'May-11': ['National Technology Day'],
  'May-12': ['International Nurses Day'],
  'May-15': ['International Day of Family'],
  'May-17': ['World Telecom Day'],
  'May-18': ['International Museum Day'],
  'May-19': ['World Hepatitis Day'],
  'May-21': ['World Anti-Terrorism Day'],
  'May-23': ['World Turtle Day'],
  'May-24': ['Commomwealth day'],
  'May-31': ['World Anti-Tobacco Day'],
  // June
  'Jun-1': ["International Children's Day"],
  'Jun-5': ['World Environment Day'],
  'Jun-8': ['World Brain Tumour Day', 'World Ocean Day'],
  'Jun-10': ['Ballpoint Pen Day'],
  'Jun-12': ['World Day Against Child Labour'],
  'Jun-14': ['World Blood Donor Day'],
  'Jun-19': ['World Sickle Cell Day'],
  'Jun-20': ['World Refugee Day'],
  'Jun-21': ['World Music Day'],
  // July
  'Jul-1': ["Doctors' Day", 'CA Day'],
  'Jul-7': ['International Cooperative Day'],
  'Jul-8': ["Writers' Day"],
  'Jul-11': ['World Population Day'],
  'Jul-26': ['Kargil Victory Day'],
  // August
  'Aug-6': ['Hiroshima day'],
  'Aug-9': ['Quit India Day', 'Nagasaki Day'],
  'Aug-12': ['International Youth day'],
  'Aug-13': ['Left Hander Day'],
  'Aug-15': ['Independence Day (India)'],
  'Aug-19': ['World Photography Day'],
  'Aug-20': ['Sadbhavna Divas'],
  'Aug-29': ['National Sports Day'],
  // September
  'Sep-4': ['World Hackers Day'],
  'Sep-5': ["Teachers' Day", 'Sanskrit Day'],
  'Sep-8': ['World Literary Day'],
  'Sep-14': ['Hindi Day'],
  'Sep-15': ["Engineer's Day"],
  'Sep-16': ['World Ozone Day'],
  'Sep-23': ['World Heart Day'],
  'Sep-26': ['Deaf Day'],
  'Sep-27': ['World Tourism Day'],
  // October
  'Oct-2': ['Gandhi Jayanti', 'International Non-Violence Day'],
  'Oct-3': ['World Habitat Day'],
  'Oct-4': ['World Animal Welfare Day'],
  'Oct-8': ['Indian Air Force Day'],
  'Oct-9': ['World Postal Day'],
  'Oct-10': ['National Postal Day', 'World Mental Health Day'],
  'Oct-12': ['World Sight Day'],
  'Oct-15': ['Global Handwashing Day'],
  'Oct-16': ['World Food Day'],
  'Oct-17': ['International Poverty Eradication Day'],
  // November
  'Nov-14': ["Children's Day", 'Diabetes Day'],
  'Nov-26': ['Law Day'],
  // December
  'Dec-1': ['World AIDS Day'],
  'Dec-4': ['Navy Day'],
  'Dec-7': ['Flag Day'],
  'Dec-10': ['Human Rights Day'],
  'Dec-11': ['UNICEF Day'],
  'Dec-14': ['National Energy Conservation Day'],
  'Dec-18': ['Minorities Rights Day'],
  'Dec-22': ['Mathematics Day'],
  'Dec-23': ['Farmers Day'],
  'Dec-25': ['Christmas'],
  'Dec-27': ['Being Human Day'],
  'Dec-28': ['Card Playing Day'],
};
const celebBdays = {
  // January
  'Jan-1': ['Sonali Bendre', 'Nana Patekar', 'Asrani', 'Vidya Balan'],
  'Jan-5': ['Deepika Padukone', 'A.R. Rehmaan'],
  'Jan-7': ['Bipasha Basu'],
  'Jan-9': ['Farhan Akhtar'],
  'Jan-10': ['Hrithik Roshan'],
  'Jan-13': ['Imran Khan'],
  'Jan-17': ['Javed Akhtar'],
  'Jan-18': ['Minissha Lamba'],
  'Jan-21': ['Kim Sharma'],
  'Jan-24': ['Om Prakash'],
  'Jan-27': ['Shreyas Talpade', 'Bobby Deol'],
  // February
  'Feb-1': ['Jackie Shroff'],
  'Feb-2': ['Shamita Shetty'],
  'Feb-4': ['Urmila Matondkar'],
  'Feb-5': ['Abhishek Bachchan'],
  'Feb-9': ['Amrita Singh'],
  'Feb-11': ['Tina Munim'],
  'Feb-12': ['Pran'],
  'Feb-15': ['Randhir Kapoor'],
  'Feb-20': ['Anu Kapoor'],
  'Feb-23': ['Bhagyashree'],
  'Feb-24': ['Pooja Bhatt'],
  'Feb-25': ['Shahid Kapoor', 'Danny Denzongpa'],
  // March
  'Mar-5': ['Uday Chopra'],
  'Mar-7': ['Anupam Kher'],
  'Mar-11': ['Poonam Pandey'],
  'Mar-12': ['Javed Khan'],
  'Mar-14': ['Aamir Khan'],
  'Mar-18': ['Shashi Kapoor'],
  'Mar-19': ['Tanushree Dutta'],
  'Mar-20': ['Kangana Ranaut'],
  'Mar-21': ['Rani Mukherjee'],
  'Mar-24': ['Emraan Hashmi'],
  'Mar-28': ['Akshay Khanna', 'Moon Moon Sen'],
  // April
  'Apr-2': ['Ajay Devgan'],
  'Apr-4': ['Parveen Babi'],
  'Apr-5': ['Rashmika Mandanna'],
  'Apr-7': ['Jeetendra', 'Jackie Chan'],
  'Apr-9': ['Jaya Bachchan'],
  'Apr-10': ['Ayesha Takia'],
  'Apr-16': ['Lara Dutta'],
  'Apr-19': ['Arshad Warsi'],
  'Apr-20': ['Mamta Kulkarni'],
  'Apr-23': ['Yana Gupta'],
  'Apr-24': ['MacMohan'],
  'Apr-26': ['Moushmi Chatterjee'],
  'Apr-28': ['Samantha Ruth', 'Sharman Joshi'],
  // May
  'May-1': ['Anushka Sharma'],
  'May-10': ['Ravi Bahl'],
  'May-11': ['Pooja Bedi'],
  'May-13': ['Sri Sri Ravishankar', 'Sunny Leone'],
  'May-15': ['Madhuri Dixit'],
  'May-17': ['Pankaj Udhas'],
  'May-18': ['Farida Jalal'],
  'May-20': ['Kamal Hassan'],
  'May-29': ['Pankaj Kapoor'],
  'May-30': ['Paresh Rawal'],
  // June
  'Jun-1': ['R.Madhavan'],
  'Jun-2': ['Sonakshi Sinha', 'Jacqueline Fernandez'],
  'Jun-3': ['Mauli Dave'],
  'Jun-4': ['Balasubhramaniyam'],
  'Jun-6': ['Sunil Dutt'],
  'Jun-7': ['Amrita Rao', 'Ekta Kapoor'],
  'Jun-8': ['Shilpa Shetty', 'Dimple'],
  'Jun-9': ['Sonam Kapoor', 'Celina Jaitley'],
  'Jun-10': ['Mika Singh'],
  'Jun-14': ['Shekhar Suman'],
  'Jun-16': ['Mithun'],
  'Jun-17': ['Anupam Kher'],
  'Jun-19': ['Saloni (comedy circus)'],
  'Jun-22': ['Amrish Puri'],
  'Jun-23': ['Raj Babbar'],
  'Jun-25': ['Karishma', 'Aftab', 'Satish Shah'],
  // July
  'Jul-1': ['Sudesh Bhosle'],
  'Jul-6': ['Ranveer'],
  'Jul-7': ['Kailash', 'Dhoni'],
  'Jul-8': ['Neetu Singh'],
  'Jul-9': ['Tabassum'],
  'Jul-10': ['Aloknath'],
  'Jul-16': ['Katrina Kaif'],
  'Jul-18': ['Priyanka'],
  'Jul-20': ['Nasiruddin', 'Gracy Singh'],
  'Jul-22': ['Mukesh Khanna'],
  'Jul-23': ['Himesh Reshammiya'],
  'Jul-24': ['Manoj Kumar'],
  'Jul-27': ['Kriti Sanon'],
  'Jul-29': ['Sanjay Dutt'],
  'Jul-30': ['Sonu Nigam', 'Sonu Sood'],
  // August
  'Aug-4': ['Arbaaz Khan'],
  'Aug-5': ['Kajol', 'Genelia'],
  'Aug-6': ['Aditya Narayan'],
  'Aug-9': ['Hanshika Motwani'],
  'Aug-11': ['Sunil Shetty'],
  'Aug-13': ['Sridevi'],
  'Aug-14': ['Johny Lever', 'Mohnish Behl'],
  'Aug-15': ['A K Hangal'],
  'Aug-16': ['Saif Ali'],
  'Aug-18': ['Preeti Jhangiani'],
  'Aug-22': ['Chiranjeev'],
  'Aug-23': ['Malaika Arora', 'Saira Baano'],
  'Aug-27': ['Neha Dhupiya'],
  'Aug-29': ['Nagarjuna'],
  // September
  'Sep-3': ['Shakti Kapoor', 'Vivek Oberoi'],
  'Sep-4': ['Rishi Kapoor'],
  'Sep-6': ['Rakesh Roshan'],
  'Sep-8': ['Asha Bhosle'],
  'Sep-9': ['Akshay Kumar'],
  'Sep-12': ['Prachi Desai', 'Ranjeet'],
  'Sep-13': ['Mahima Chaudhry'],
  'Sep-14': ['Sameera Reddy', 'Ayushmaan Khurrana'],
  'Sep-17': ['Shabana Azmi'],
  'Sep-21': ['Gulshan Grover', 'Kareena'],
  'Sep-22': ['Kumar Sanu'],
  'Sep-23': ['Prem Chopra'],
  'Sep-25': ['Divya Dutta', 'Feroz Khan'],
  'Sep-26': ['Chunky', 'Devanand', 'Archana Puran Singh'],
  'Sep-27': ['Yash Chopra'],
  'Sep-28': ['Ranbir Kapoor', 'Lata Mangeskar'],
  'Sep-29': ['Mehmood'],
  // October
  'Oct-2': ['Asha Parekh'],
  'Oct-4': ['SohaAli'],
  'Oct-6': ['Vinod Khanna'],
  'Oct-10': ['Rekha'],
  'Oct-11': ['Amitabh', 'Ronit Roy'],
  'Oct-12': ['Tinnu Anand'],
  'Oct-13': ['Ashok Kumar'],
  'Oct-16': ['Hema Malini'],
  'Oct-18': ['Om Puri'],
  'Oct-19': ['Sunny Deol'],
  'Oct-21': ['Shammi Kapoor Kulbhushan Kharbanda'],
  'Oct-22': ['Parineeti Chopra', 'Kader Khan'],
  'Oct-23': ['Malaika Arora'],
  'Oct-24': ['Mallika Sherawat'],
  'Oct-26': ['Asin', 'Ravina Tandon'],
  // November
  'Nov-1': ['Aishwarya Rai'],
  'Nov-2': ['Diana', 'Shahrukh Khan', 'Anu Malik'],
  'Nov-4': ['Tabu'],
  'Nov-7': ['Kamal Hassan'],
  'Nov-11': ['Mala Sinha', 'Johney Walker'],
  'Nov-13': ['Juhi Chawla'],
  'Nov-19': ['Daara Singh', 'Zeenat Aman', 'Sushmita Sen'],
  'Nov-20': ['Tusshar Kapoor'],
  'Nov-21': ['Helen', 'Neha Sharma'],
  'Nov-22': ['Saroj Khan'],
  'Nov-23': ['Baba Sehghal'],
  'Nov-24': ['Amol Palekar'],
  'Nov-25': ['Bappi Lahiri', 'Rakhi Sawant'],
  'Nov-26': ['Arjun Rampal'],
  // December
  'Dec-1': ['Udit Narayan'],
  'Dec-4': ['Javed Jaffri'],
  'Dec-8': ['Dharmendra'],
  'Dec-9': ['Shatrughan Sinha', 'Dia Mirza'],
  'Dec-11': ['Dilip Kumar'],
  'Dec-12': ['Rajnikant'],
  'Dec-17': ['Ritesh Deshmukh', 'John'],
  'Dec-20': ['Sohail Khan'],
  'Dec-21': ['Govinda'],
  'Dec-24': ['Anil Kapoor'],
  'Dec-27': ['Salman'],
  'Dec-29': ['Twinkle Khanna', 'Rajesh Khanna'],
};

var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function dateKey(splDate) {
  return months[splDate.getMonth()] + '-' + splDate.getDate();
}
